development:
  adapter: mysql
  user: root
  database: defogger_development

test:
  adapter: mysql
  user: root
  database: defogger_test


production:
  adapter: mysql
  user: root
  database: defogger_production
